<?php

return [
    'About project' => 'О проекте',

    'Information system "Electronic structure of atoms" is one of the most complete world databases of spectral data.' => 'Информационная система «Электронная структура атомов» – российская информационно-справочная система по спектральным данным атомов и ионов с одной из самых полных баз спектральных данных среди мировых систем.',
    'At the core of the information system lies a database with spectral data, collected from various literary sources and electronic resources. Unlike similar resources, this information system provides both tabular and graphical representation of an atomic structure for all chemical elements of the periodic table.' => 'В основе информационной системы находится база данных, собранная как из различных литературных источников, так и электронных ресурсов. В отличие от аналогов, данная информационная система по запросу пользователя обеспечивает как табличное, так и графическое представление атомной структуры всех химических элементов таблицы Д. Менделеева.',
    'The database contains information for neutral atoms, single and multiple ions. Experimental data presented for most of atoms in the database and theoretical data presented mainly for artificial and transuranium elements. The system provides a user with wide capabilities, including filtering and sorting of levels and transitions, selective representation of Rydberg and autoionization states.' => 'В базе данных представлена информация по всем атомам периодической таблицы, их однократным и многократным ионам. Для большинства элементов в базе представлены экспериментальные данные, а теоретические – в основном для трансурановых и искусственных элементов. Система предоставляет пользователю широкие возможности выборки, включая фильтрацию и сортировку уровней и переходов, селективное отображение ридберговских и автоионизационных состояний.',
    'The information system contains data on energy levels and radiative transitions, the values of the intensity and the probability of transitions, oscillator strengths, lifetimes of levels, excitation cross section.' => 'Информационная система содержит данные об уровнях энергии и радиационных переходах, значения интенсивности и вероятности переходов, силы осцилляторов, времени жизни уровней, сечения возбуждения.',
    '"Electronic structure of atoms" allows next main types of usage' => 'Система обеспечивает возможность основных видов работы пользователя',
    'obtaining general background information about the atom or ion' => 'получение общей справочной информации об атоме или ионе',
    'obtaining obtaining information about levels of elements in a tabular form. Currently, the system contains information on {0} levels' => 'получение информации об уровнях элементов в табличном виде. В настоящее время в системе содержится информация по {0} уровням',
    'obtaining information about transitions of elements in a tabular form. Currently, the system contains information on {0} transitions' => 'получение информации по переходам элементов в табличном виде. В настоящее время в системе содержится информация по {0} переходам',
    'obtaining graphical representation in form of parametrized color spectrograms and Grotrian diagrams' => 'получение графического представления - цветных спектрограмм и диаграмм Гротриана для всех атомных систем по заданному элементу и набору параметров',
    'Grotrian diagrams is a well-known cognitive graphical representation of the structure of an atom or ion. In common view, the Grotrian diagram is a chart with sorted energy levels on the vertical scale and transitions in a form of lines, connecting energy levels. Transitions are selected from total number of transitions in accordance with priority rules and user options. A number of original algorithms implemented in the "Electronic structure of atoms" provide efficient selection of the lines. Thus Grotrian diagram remains legible for atomic systems with any number of transitions.' => 'Диаграммы Гротриана – графическое изображение спектральных данных, основное назначение которого - дать наглядное представление о строении отдельного атома или иона. В общем виде, диаграмма Гротриана – упорядоченные в соответствии с вертикальной шкалой энергий уровни атома или иона и соединяющие их линии переходов, отобранные из общего числа переходов в соответствии с правилами приоритета и пользовательскими опциями. Ряд оригинальных алгоритмов, реализованных в информационной системе «Электронная структура атомов», обеспечивает эффективный отбор линий, при котором диаграмма Гротриана остается читаемой для атомных систем с любым числом переходов.',
    'The information system is designed for scientists, engineers and students, dealing with atomic spectroscopy, plasma physics, quantum electronics, astrophysics and related disciplines, as well as in education.' => 'Информационная система предназначена для научных сотрудников, инженеров и студентов, занимающихся вопросами атомной спектроскопии, физики плазмы, квантовой электроники, астрофизики и смежных специальностей, а также в образовании для подготовки специалистов.',
    'The project is supported by Russian foundation for basic research. The copyright to the database and software are protected by RF Federal service for intellectual property. (Certificates №2009620361, №2011610094, №2011616297, patent №117178).' => 'Работа ведется при поддержке РФФИ (грант №16-37-60094-мол_а_дк, №16-07-00910-а), ФЦП Кадры (подробнее...). Авторские права на базу данных и программное обеспечение защищены Роспатентом (св-ва №2009620361, №2011610094, №2011616297, патент №117178).',
];